// <auto-generated />
namespace LearniVerseNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedtrckingHistorytoorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedtrckingHistorytoorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202410101509534_Added trcking History to order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
