// <auto-generated />
namespace LearniVerseNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addedquestionnumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedquestionnumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202405070929542_Added question number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
