// <auto-generated />
namespace LearniVerseNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addedpaymentformmembrshipsidtpthemembrshiptable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedpaymentformmembrshipsidtpthemembrshiptable));
        
        string IMigrationMetadata.Id
        {
            get { return "202408121308193_Added payment form membrships id tp the membrship table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
